package Modelo;
// Generated 30-oct-2017 13:31:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empleados generated by hbm2java
 */
public class Empleados  implements java.io.Serializable {


     private Integer idEmpleado;
     private String nombres;
     private String apellidos;
     private String documento;
     private String correo;
     private String contrasena;
     private String perfil;
     private Set<Cotizaciones> cotizacioneses = new HashSet<Cotizaciones>(0);

    public Empleados() {
    }

	
    public Empleados(String nombres, String apellidos, String documento, String correo, String contrasena, String perfil) {
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.documento = documento;
        this.correo = correo;
        this.contrasena = contrasena;
        this.perfil = perfil;
    }
    public Empleados(String nombres, String apellidos, String documento, String correo, String contrasena, String perfil, Set<Cotizaciones> cotizacioneses) {
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.documento = documento;
       this.correo = correo;
       this.contrasena = contrasena;
       this.perfil = perfil;
       this.cotizacioneses = cotizacioneses;
    }
   
    public Integer getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(Integer idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(String documento) {
        this.documento = documento;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public String getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(String perfil) {
        this.perfil = perfil;
    }
    public Set<Cotizaciones> getCotizacioneses() {
        return this.cotizacioneses;
    }
    
    public void setCotizacioneses(Set<Cotizaciones> cotizacioneses) {
        this.cotizacioneses = cotizacioneses;
    }




}


